baseURL = "/"
languageCode = "de"
title = "Docker"
theme = "hugo-coder"

[params]
  author = "Bernd Öggl, Michael Kofler"
  info = "Ein Buch über Docker für DevOps"
  description = "Beispiele, Cloud und viel mehr"
  avatarurl = "/images/docker3.jpg"
  hideCredits = true
  hideCopyright = false
  faviconSVG = ""
  favicon_32 = ""
  favicon_16 = ""
  manifest = ""

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/docbuc/"
    icon = "fa fa-github"
[[params.social]]
    name = "Amazon"
    weight = 2
    icon = "fa fa-amazon"
    url = "https://www.amazon.de/Docker-Praxisbuch-Entwickler-DevOps-Teams-Windows/dp/3836261766/"
[[params.social]]
    name = "Rheinwerk"
    weight = 2
    url = "https://www.rheinwerk-verlag.de/docker_4599/"
[[params.social]]
    name = "🐘 bö"
    weight = 3
    url = "https://mastodon.social/@Berndo"
    rel = "me"
[[params.social]]
    name = "🐘 mk"
    weight = 3
    url = "https://home.social/@michaelkofler"

# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url = "/posts/"
[[menu.main]]
  name = "Inhalt"
  weight = 2
  url = "/inhalt/"
[[menu.main]]
  name = "Errata"
  weight = 3
  url = "https://kofler.info/buecher/docker/errata/"
[[menu.main]]
  name = "Über das Buch"
  weight = 4
  url = "/about/"
